### ISSUE TITLE
Installation of module fails : Odoo 8

### ISSUE THREAD

**Issue by andreassantoro** [acsone/acsone-addons#46]
Hi, I installed all dependencies for this module.
But if I try to install, I receive the following error.
Some advice?

OpenERP Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 500, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 517, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 280, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 733, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 340, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 149, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo-server/openerp/modules/module.py", line 312, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/opt/odoo/odoo-server/openerp/modules/module.py", line 77, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/custom/addons/hr_utilization/**init**.py", line 31, in <module>
    from . import hr_utilization
ImportError: cannot import name hr_utilization

**Comment by sbidoul** [comment]
Hello,

I have recently tested the module on our 8.0 instance, and I do not have this error.

I do have some display issue, but it installs correctly.

So it's probably an issue with your setup but we would need more details to help you further.

-sbi
